//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikWebApplication.Form.Inventory.FluidControl.Fuel {
    
    
    public partial class inv01h05fcReportViewer {
        
        /// <summary>
        /// reportViewer_inv01h05fc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.ReportViewer.Html5.WebForms.ReportViewer reportViewer_inv01h05fc;
    }
}
